version: '3.2'
services:

  postgres:
    image: "postgres:12"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

  rskj:
    image: rsksmart/rskj:HOP-4.4.0
    entrypoint:  ["java", "-cp", "rsk.jar", "co.rsk.Start" ]
    ports:
      - "4444:4444"
      - "4445:4445"
    volumes:
      - ./docker/rskj/logback.xml:/etc/rsk/logback.xml
      - ./docker/rskj/node.conf:/etc/rsk/node.conf
  
  dev-ticker:
    image: "rsksmart/rollup-dev-ticker:1.0.0-beta"
    env_file:
      - ./etc/env/docker.env
    volumes:
      - ./etc/tokens/:/etc/tokens

  zk:
    image: "rsksmart/rollup-environment:1.1.0-beta"
    depends_on:
      - postgres
      - rskj
      - dev-ticker
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /usr/src/keys:/usr/src/keys
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV_OVERRIDE=docker
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE="50g"
      - CI=1
      - CAROOT=/usr/src/zksync
      - NODE_EXTRA_CA_CERTS=/usr/src/zksync/rootCA.pem
      - CODE_COVERAGE=true
