version: '3.2'
services:

  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: ./volumes/postgres
      target: /var/lib/postgresql/data
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust

  rskj:
    image: rsksmart/rskj:HOP-4.4.0
    entrypoint:  ["java", "-cp", "rsk.jar", "co.rsk.Start" ]
    ports:
      - "4444:4444"
      - "4445:4445"
    volumes:
      - type: bind
        source: ./volumes/rskj
        target: /etc/rsknode
      - ./docker/rskj/logback.xml:/etc/rsk/logback.xml
      - ./docker/rskj/node.conf:/etc/rsk/node.conf
      - ./docker/rskj/data:/var/lib/rsk/.rsk
    healthcheck:
      # How to perform an healthcheck against an endpoint without curl/wget
      # https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa
      test: "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/4444' || exit 1"
      interval: 10s
      timeout: 1m
      retries: 5
      start_period: 15s
  
  dev-ticker:
    image: "rsksmart/rollup-dev-ticker:1.1.0-beta"
    env_file:
      - ./etc/env/${ZKSYNC_ENV-dev}.env
      - ./etc/env/${ENV_OVERRIDE-deploy}.env
    ports:
      - "9876:9876"
    volumes:
      - ./etc/tokens/:/etc/tokens
      
  tesseracts:
    image: "adria0/tesseracts"
    command: --cfg /tesseracts.toml -vvv
    ports:
      - "8000:8000"
    volumes:
    - ./etc/tesseracts/tesseracts.toml:/tesseracts.toml
    - type: bind
      source: ./volumes/tesseracts
      target: /var/lib/tesseracts/data
    depends_on:
      rskj:
        condition: service_healthy

  elastic:
    image: elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
