# Whether to ask user about dangerous actions or not
zksync_action="dont_ask"

# Miscellaneous options for different infrastructure elements
[misc]
# Download setup files from SETUP_NETWORK_DIR if PROVER_DOWNLOAD_SETUP=1 or use local files if PROVER_DOWNLOAD_SETUP=0
prover_download_setup=false
# Network location of setup files
prover_setup_network_dir="-"

# Used to configure env for docker
docker_dummy_prover=true

# API key for the analytics script
etherscan_api_key="unset"

# Configuration for the fee seller script
max_liquidation_fee_percent=5
# fee_account_private_key is set in `private.toml`

reserve_fee_accumulator_address="unset"

established_assets_for_withdrawing_through_zksync="RBTC,RIF,RDOC"

# Format of logs in stdout could be "plain" for development purposes and "json" for production
log_format="plain"

sentry_url="unset"

# The address of the regenesis multisig smart contract <env_address>
regenesis_multisig_address="0xAA7113B9de498556dC76eDFEFc57681083c861C1"

# The number of parter signatures we need to get for the regenesis
regenesis_threshold=2


# Token in which we want accept fees for permissionless token listing <env_address>
listing_fee_token="0x0000000000000000000000000000000000000000"

# The number of token (in wei-RBTC) we want to be payed for listing a token
listing_fee=660000000000000

# Listing cap, the maximum number of tokens which can be listed (2^16 - 100 by default)
listing_cap=65436

# The address which will receive funds from permissionless token listings <env_address>
listing_treasury="0xde2e44c1797859DcF9bA408Fc19398e20DfF3701"

# Security council parameters <env_address>
security_council_members_number=3
security_council_members=["0x07473f4Fd742DaE806EA0f95E8522490aFf10250","0x33C2630eE0ac5423872e45b9e5Fb747429D6Fd77","0x9aa96eE486B8D0448771218baBD14bE60823C322"]

security_council_threshold=2
