name: Mark PR as Draft
description: Converts the given pull request to a draft

inputs:
  token:
    required: true
    description: Github Token used to make API request to mutate pull requests
    default: ${{ github.token }}
  pull-request-node-id:
    required: true
    description: GitHub pull request node id
    default: ${{ github.event.pull_request.node_id }}

runs:
  using: composite
  steps:
    - name: Mark as draft
      shell: bash
      run: |
        echo ${{ inputs.token }} | gh auth login --with-token
        gh api graphql -F id=${{ inputs.pull-request-node-id }}  -f query='
          mutation($id: ID!) {
            convertPullRequestToDraft(input: { pullRequestId: $id }) {
              pullRequest {
                id
                number
                isDraft
              }
            }
          }
        '