name: Simulation tool tests
on: 
  push:
    paths:
      - 'infrastructure/simulation-tool'
      - 'infrastructure/zk/src/simulator.ts'
      - 'infrastructure/zk/src/test.ts'
  
jobs:
  simulation-tool-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: setup-env
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH

      - name: start-services
        run: |
          docker-compose -f docker-compose.ci.yml up --build -d zk

      - name: init
        run: |
          ci_run zk
          ci_run zk run yarn

      - name: run simulation-tool test
        run: zk test simulator
